// NOTE: This file is auto-generated by React Cosmos.
// It imports all fixture and decorator modules, making them available to the
// React Cosmos renderer along with the renderer config.

import type { RendererConfig, UserModuleWrappers } from 'react-cosmos-core';

import * as fixture0 from './src/app/lib/components/Hello.fixture.js';

export const rendererConfig: RendererConfig = {
  "webSocketUrl": "ws://172.22.250.216:5000",
  "rendererUrl": "http://localhost:4501/cosmos/<fixture>"
};

const fixtures = {
  'src/app/lib/components/Hello.fixture.js': { module: fixture0 }
};

const decorators = {};

export const moduleWrappers: UserModuleWrappers = {
  lazy: false,
  fixtures,
  decorators
};
